image: maven:3.6.3-jdk-11

variables:
  PROJECT_KEY: "air-quality-service"
  SONAR_TOKEN: "b3c05d385f6d359c36cb4d2de9e8631a9edef0bf"
  SONAR_HOST_URL: "https://sonarcloud.io/"
  GIT_DEPTH: 0
  ORGANIZATION: "vasco"


stages:
  - Analysis
  - Test
  - Deploy

unit-test:
  stage: Test
  script:
    - mvn -B test
  except:
    - merge_requests
    - master

integration-test:
  stage: Test
  script:
    - mvn integration-test '-Dtest=!%regex[.*UI.*]'
  only:
    - merge_requests
    - master

sonarqube-check:
  stage: Analysis
  script:
    - mvn -B -q verify sonar:sonar -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=${ORGANIZATION}
      -Dsonar.qualitygate.wait=true
      '-Dtest=!%regex[.*UI.*]'

  allow_failure: true
  only:
    - merge_requests
    - master

production:
  stage: Deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=tqs-air-quality-service --api-key=$HEROKU_API_KEY
  only:
    - master
