image: maven:3.6.3-jdk-11

variables:
  PROJECT_KEY: "Air Quality Service"
  SONAR_TOKEN: "b3c05d385f6d359c36cb4d2de9e8631a9edef0bf"
  SONAR_HOST_URL: "https://sonarcloud.io/"
  GIT_DEPTH: 0
  ORGANIZATION: "vasco"


stages:
  - Analysis

sonarqube-check:
  stage: Analysis
  script:
    - mvn sonar:sonar -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.host.url=${SONAR_HOST_URL}
          -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=${ORGANIZATION}
          -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - master
